# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e65b7459238592b91f471ee875cf1e7932db53a2ad0220a3f0f03e2c9a0720445d7adb48a4d956a1c1044c0e0f85ff093cd051b81df032751e53f60041ba652e

test:
  secret_key_base: 145dbe4f2f71d9c6f148305dd0527fac32ba861741fad429cc56b7f0973fefc567575cad92dc39925d1bb6b4774f343700ded66d5394fc8516e9444aa238d912

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
